### ISSUE TITLE
Infinite (looping) iterator?

### ISSUE THREAD

**Issue by nabijaczleweli** [andylokandy/arraydeque#1]
AFAICS. the only iterators are single-pass. Having a loop-forever iterator would be neat.

**Comment by goandylok** [comment]
That's a good idea, I will consider it.
But there are some problems on implementation strategy. 
- `no_std support`. How to store a infinite iter closure without allocation.
- `thread safety`. Should the infinite iter borrows the queue? If we allow pushing items when somebody holding a iter, it means the borrow checker is cheated. So, we need mark the whole queue not `Send` for thread safety.

**Comment by andylokandy** [comment]
Postponed.
