### ISSUE TITLE
Bad use of `mem::uninitialized` in constructor

### ISSUE THREAD

**Issue by pnkfelix** [andylokandy/arraydeque#12]
Spawned from https://github.com/rust-lang/rust/issues/58684

The following test is likely to fail in the current code base, at least for many versions of `rustc`.

```rust
    #[test]
    fn test_option_encoding() {
        let tester: ArrayDeque<[Box<()>; 100], Wrapping> = ArrayDeque::new();
        assert!(Some(tester).is_some());
    }
```

The reason it will fail is because `ArrayDeque::new()` is using `mem::uninitialized` to create the array itself, which is discouraged because the resulting value will tend to yield undefined behavior unless the type is valid for all possible bit patterns. (And an easy example of a type that is not valid for all possible bit patterns is `Box<T>`, since it must be non-null.)

The test above is demonstrating how violating this rule can break invariants like `Some(E).is_some()` for any `E`.

 * One potential fix for this has been [pointed out](https://github.com/rust-lang/rust/issues/58684#issuecomment-469671952) by oli: Use an untagged union instead of `mem::uninitialized`.
 * Another potential fix would be to use `MaybeUninit` instead of `ManuallyDrop`, as [pointed out](https://github.com/rust-lang/rust/issues/58684#issuecomment-469678452) by nagisa.

Neither of these fixes is available in stable Rust today, though. (untagged unions only support `Copy` data if you're on stable.)

**Comment by pnkfelix** [comment]
Since this library was inspired by bluss/arrayvec, see  also https://github.com/bluss/arrayvec/issues/105 , which discusses similar issues, and PRs https://github.com/bluss/arrayvec/pull/114 and  https://github.com/bluss/arrayvec/pull/116, which demonstrate the changes that library has adopted in attempting to resolve those problems.

**Comment by andylokandy** [comment]
Thanks! This is a well-known issue that I knew when MaybeUninit RFC came out, and arrayvec shows me a good trick to solve it. Thanks for bringing this up.
