### ISSUE TITLE
Use const generics instead of `generic-array`

### ISSUE THREAD

**Issue by YuhanLiin** [andylokandy/arraydeque#18]
Now that Rust supports const generics, `ArrayDeque` should take the capacity as a type parameter rather than an array type. This prevents the deque from using smaller index types, but that isn't a big drawback in practice. `ArrayVec` is already using const generics, and their array index is set to `u32`.

**Comment by elpiel** [comment]
@andylokandy I would also benefit from the implementation of `Array` for `[T; CONST_GENERIC]`.

**Comment by andylokandy** [comment]
It's a good idea to migrate to const generic at this time. But the other project has occupied me too much time right now. For anyone interested in, pull requests are always welcome!
