### ISSUE TITLE
Mininum rust version

### ISSUE THREAD

**Issue by rillian** [andylokandy/arraydeque#5]
Hi. I notice you're testing against Rust 1.15.0 as a minimum supported version. If this is for compatibility with Firefox, I wanted to let you know that we [bumped that minimum](https://bugzilla.mozilla.org/show_bug.cgi?id=1374807) to 1.17.0 today, so if you'd prefer to use more recent language features, that's an option.

**Comment by goandylok** [comment]
Thanks a lot for your suggestion. It will be nice to unlock more language features. XD
